analyse_metric_task:
  description: >
    Analyse the metrics of each pod, service, deployment from the {namespace} namespace in Prometheus, focusing on identifying trends, anomalies, and potential issues. Execute necessary queries to gather relevant data. Provide a comprehensive report based on this analysis.
  expected_output: >
    A detailed report that includes:
    - Identified trends and patterns in the data.
    - Any detected anomalies or unusual behavior.
    - Recommendations for potential diagnostic tasks or further investigation if needed.
    - Clear, data-backed justifications for all insights and recommendations.

execute_query_task:
  description: >
    Execute a custom Prometheus query to retrieve specific metrics needed for detailed analysis. Ensure the query is sanitized and valid.
  expected_output: >
    The result of the executed query, formatted as a clear and concise summary of the metrics retrieved.

diagnose_issue_task:
    description: >
        Find the root cause of the anomaly.
        Use the insights from the analyse_metric_task to identify the root cause.
    expected_output: >
        A diagnostic report with the root cause of the anomaly.

provide_solution_task:
    description: >
        Find a solution to the root cause of the anomaly.
        Use the insights from the diagnostic_task to find a solution.
    expected_output: >
        A report with the solution to the root cause of the anomaly.

report_incident_task:
    description: >
        Create an incident report with the findings from the previous tasks.
    expected_output: >
        A complete incident report with the findings from the previous tasks.