"""Create AgentRunPublic and AgentRunsPublic

Revision ID: 5c64dfa8b35f
Revises: af8b32840026
Create Date: 2024-07-03 09:44:52.404760

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c64dfa8b35f'
down_revision = 'af8b32840026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
