"""Fix auto datetime

Revision ID: 8bf641f25f29
Revises: f157ff9677da
Create Date: 2024-07-03 17:22:09.946983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8bf641f25f29'
down_revision = 'f157ff9677da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
