"""Add agent run and event tables

Revision ID: a4418f32335e
Revises: fe56fa70289e
Create Date: 2026-06-10 18:49:13.395501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a4418f32335e'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentrun',
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agentrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('agentrun')
    # ### end Alembic commands ###
