"""Create langgraph events

Revision ID: f157ff9677da
Revises: 5c64dfa8b35f
Create Date: 2024-07-03 16:57:50.948126

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f157ff9677da'
down_revision = '5c64dfa8b35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agentrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_lgmessage_message_type', table_name='lgmessage')
    op.drop_table('lgmessage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgmessage',
    sa.Column('message_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_calls', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agentrun.id'], name='lgmessage_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lgmessage_pkey')
    )
    op.create_index('ix_lgmessage_message_type', 'lgmessage', ['message_type'], unique=False)
    op.drop_table('event')
    # ### end Alembic commands ###
