"""Change id to uuid

Revision ID: fe579749e89c
Revises: 8bf641f25f29
Create Date: 2024-07-06 13:39:03.927157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fe579749e89c'
down_revision = '8bf641f25f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agentrun', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.GUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('agentrun_id_seq'::regclass)"))
    op.alter_column('event', 'run_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.GUID(),
               existing_nullable=True)
    op.alter_column('event', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.GUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'id',
               existing_type=sqlmodel.sql.sqltypes.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('event', 'run_id',
               existing_type=sqlmodel.sql.sqltypes.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('agentrun', 'id',
               existing_type=sqlmodel.sql.sqltypes.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('agentrun_id_seq'::regclass)"))
    # ### end Alembic commands ###
